[package]
name = "exec"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
catalog.workspace = true
sql.workspace = true
storage.workspace = true
types.workspace = true
