[package]
name = "exec"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
types = { path = "../types" }
sql = { path = "../sql" }
catalog = { path = "../catalog" }
storage = { path = "../storage" }