[package]
name = "catalog"
version = "0.1.0"
edition = "2024"

[dependencies]
types = { path = "../types" }
storage = { path = "../storage" }
serde={workspace=true}
snafu={workspace=true}
crc32fast = "1.5.0"
